### ISSUE TITLE
Does this work offline?

### ISSUE THREAD

**Issue by BigWillie** [karlwestin/pouchdb-sync-to-anything#2]
I have a project that uses Mongo on the backend. Been told that I need to make it into a Progressive Web App... offline functionality etc..

With pouchdb-sync-to-anything, am I able to save any form post data to the local pouchdb and have it automagically post to my API as soon as the app is online again?

Do I need to handle the syncid (create one etc?)

When offline - I can read the data from pouch... when online I can read it from the server. This is idea :)

**Comment by karlwestin** [comment]
This plugin handles the scenario when you wanna WRITE data to your API, but you want to be able to store it offline

You store data in pouchdb on the client, and when you go online, you can initiate an upload to your api

Unfortunately i have not developed it to send data both ways yet.

**Comment by BigWillie** [comment]
Thanks. Will it detect when online - or will I have to do the detection? One way is fine by me - we can make api calls to pull stuff down and write it into pouch if needs be

**Comment by karlwestin** [comment]
I'm sorry it will not detect that, you'll have to detect it and kick off the replication when you have an appropriate event

This plugin was orginally written for a very specific use case, where we preferred manually triggering a sync rather than detecting network, but i hope it can help you and its super cool that you're looking at it!

**Comment by BigWillie** [comment]
That's cool - I'm already detecting when online / offline. Although - it only detects if there if connected to network, I can listen to the response... if successful I can remove the doc from pouch (or flag it somehow) otherwise I can trigger the process again. Will pull tonight - thanks!
